version: "3"
services:
  web_service:
    container_name: starter_web
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
    - "3001:3001"
    - "9229:9229"
    volumes:
      - .:/app
    depends_on:
    - db_service
    networks:
    - network_starter

  db_service:
    container_name: starter_db
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    ports:
    - "5432:5432"
    networks:
    - network_starter

networks:
  network_starter:
    driver: bridge
