version: "3"
services:
  web_selina:
    container_name: web_selina
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
    - "3001:3001"
    - "9229:9229"
    volumes:
      - .:/app
    depends_on:
    - db_selina
    networks:
    - network_selina

  db_selina:
    container_name: db_selina
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=selina_db
    ports:
    - "5432:5432"
    networks:
    - network_selina

networks:
  network_selina:
    driver: bridge
